Feat(Boostrap): Add ZPlug. Minor indentation fixes

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -7,13 +7,13 @@ COLOR_GREEN="\x1b[32;01m"
 COLOR_RESET="\x1b[39;49;00m"
 
 # Check that an executable exists
-function executableCheck {
-    local EXE=$1
-    local NAME=$2
-    if [ "$EXE" == "0" ]; then
-        echo -e $COLOR_RED"💥  ${NAME} was not found. Check the installation requirements"$COLOR_RESET
-        exit 1
-    fi
+function executableCheck() {
+  local EXE=$1
+  local NAME=$2
+  if [ "$EXE" == "0" ]; then
+    echo -e $COLOR_RED"💥  ${NAME} was not found. Check the installation requirements"$COLOR_RESET
+    exit 1
+  fi
 }
 
 echo -e "🚀  Bootstrapping @tagoro9 dotfiles..."
@@ -25,10 +25,12 @@ if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
     echo -e "🛠  Installing Homebrew..."
     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
     exit 1
+  else
+    echo -e "🛠  Updating brew"
+    brew update >/dev/null 2>&1
   fi
 
-
-  brew bundle check >/dev/null 2>&1  || {
+  brew bundle check >/dev/null 2>&1 || {
     echo -e "🛠  Installing Homebrew dependencies…"
     brew bundle
   }
@@ -44,19 +46,27 @@ if [ ! -d "$OH_MY_ZSH" ]; then
   sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
 fi
 
+# Install zplug if not there
+ZPLUG=~/.zplug
+if [ ! -d "$ZPLUG" ]; then
+  echo -e "🛠   Installing zplug"
+  unset ZPLUG_HOME
+  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
+fi
+
 # Install vim-plug if not there
 VIM_PLUG=~/.vim/autoload/plug.vim
 if [ ! -f "$VIM_PLUG" ]; then
-echo -e "🛠   Installing vim-plug…"
-curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
+  echo -e "🛠   Installing vim-plug…"
+  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
 fi
 
 # Install tpm if not there
 TPM=~/.tmux/plugins/tpm
 if [ ! -d "$TPM" ]; then
-echo -e "🛠   Installing tmp…"
-git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
+  echo -e "🛠   Installing tmp…"
+  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
 fi
 
 echo -e $COLOR_GREEN"✅  Done\n"$COLOR_RESET
